### ISSUE TITLE
Bugs with new version of 'river' in windows，can you provide the version of 'river' and the platform which you use in this project？thanks！

### ISSUE THREAD

**Issue by ywang-art** [Western-OC2-Lab/PWPAE-Concept-Drift-Detection-and-Adaptation#1]
![X$0DJAR(VU_U L6 GV%T TS](https://user-images.githubusercontent.com/80510097/158348214-39d5d049-1f2d-411d-99a1-ec9057482b55.png)

**Comment by LiYangHart** [comment]
The River version for this code is 0.1.0.
