### ISSUE TITLE
How this file "./data/cic_0.01km.csv" is generated?

### ISSUE THREAD

**Issue by jiamo** [Western-OC2-Lab/PWPAE-Concept-Drift-Detection-and-Adaptation#2]
I didn't find the file(with same csv struct) from the original CICIDS-2017 dataset?

**Comment by LiYangHart** [comment]
You can download the dataset from their original website: https://www.unb.ca/cic/datasets/ids-2017.html
And simply combine all the datasets. Due to the file size limitation of Github (25MB), I can only upload the subset in this repo.

**Comment by LiYangHart** [comment]
By the way, the generation process of the subset can be found here: https://github.com/Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning/blob/main/MTH_IDS_IoTJ.ipynb
